### ISSUE TITLE
Curl can't find cainfo, when doing https request

### ISSUE THREAD

**Issue by bartv2** [chillerlan/php-httpinterface#1]
Disabling setting the CURLOPT_CAINFO option to null fixes this issue. Adding this option to the array only when ca_info is set should fix this issue.

**Comment by codemasher** [comment]
Thank you for the info! I should state somewhere that ca certificate (or bundle) is necessary/mandatory for HTTPS. I'll also look into a workaround to not run into errors otherwise.

**Comment by codemasher** [comment]
This is actually handled over here: https://github.com/chillerlan/php-httpinterface/blob/339f552c658b57d4b100b18ddad31199478e2f38/src/CurlHandle.php#L121
I think the problem is rather that `CURLOPT_SSL_VERIFYPEER` is set to `true` by default, which then requires the cert- I think in an earlier version of the curl client i had this value depending on the existence of a cert.

**Comment by bartv2** [comment]
The ca bundle is available on the system, and the connection works when i remove that line 121. I don't like your solution, i think only setting CURLOPT_CAINFO when $this->options->ca_info is a file would work better. When this is not specifically set the system default will be used.

**Comment by codemasher** [comment]
Oh right, i didn't think about the system CA. But what would be a reliable way to check that? Or should i drop the check at all and leave the problem up to the user (which makes up 99% of SO questions about `CURLOPT_SSL_VERIFYPEER`)?

edit: brrrrr https://github.com/guzzle/guzzle/blob/master/src/functions.php#L160

**Comment by bartv2** [comment]
That function is only used in a very limited situation (streamHandler and php 5.?) For curl they do this: https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlFactory.php#L326 I think that is the most flexible. Disabling CURLOPT_SSL_VERIFYPEER should be a last resort, maybe in the error message point to a checklist/steps to check/solve connection errors

**Comment by bartv2** [comment]
Thanks, looks good
